version: '3.8'

services:
  supabase:
    image: supabase/studio:latest
    ports:
      - "5432:5432"  # Postgres
      - "54321:54321"  # Studio
      - "54322:54322"  # API
      - "54323:54323"  # Auth
      - "54324:54324"  # Storage
    environment:
      POSTGRES_PASSWORD: your-super-secret-password
      JWT_SECRET: your-super-secret-jwt-token
      ANON_KEY: your-anon-key
      SERVICE_ROLE_KEY: your-service-role-key
    volumes:
      - ./supabase:/supabase
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 